import type { PartialBlock } from '@blocknote/core';
import { KnowledgeArtifact } from './knowledge-artifacts';

export type Note = {
  id: number;
  title: string;
  content?: PartialBlock[];
  embedding?: number[] | null;
  createdAt: string;
  updatedAt: string;
  userId: string;
  artifacts: KnowledgeArtifact[];
};

// For creating a note, omit fields that are generated by the backend
export type NoteCreate = Omit<Note, 'id' | 'createdAt' | 'updatedAt'>;

// If you want to enforce all fields for update (PUT), use:
export type NoteUpdate = Omit<Note, 'createdAt' | 'updatedAt' | 'artifacts'>;
