/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotesImport } from './routes/_notes'
import { Route as IndexImport } from './routes/index'
import { Route as NotesCreateIndexImport } from './routes/_notes/create/index'
import { Route as NotesNoteIdIndexImport } from './routes/_notes/$noteId/index'

// Create/Update Routes

const NotesRoute = NotesImport.update({
  id: '/_notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotesCreateIndexRoute = NotesCreateIndexImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => NotesRoute,
} as any)

const NotesNoteIdIndexRoute = NotesNoteIdIndexImport.update({
  id: '/$noteId/',
  path: '/$noteId/',
  getParentRoute: () => NotesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_notes': {
      id: '/_notes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/_notes/$noteId/': {
      id: '/_notes/$noteId/'
      path: '/$noteId'
      fullPath: '/$noteId'
      preLoaderRoute: typeof NotesNoteIdIndexImport
      parentRoute: typeof NotesImport
    }
    '/_notes/create/': {
      id: '/_notes/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof NotesCreateIndexImport
      parentRoute: typeof NotesImport
    }
  }
}

// Create and export the route tree

interface NotesRouteChildren {
  NotesNoteIdIndexRoute: typeof NotesNoteIdIndexRoute
  NotesCreateIndexRoute: typeof NotesCreateIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdIndexRoute: NotesNoteIdIndexRoute,
  NotesCreateIndexRoute: NotesCreateIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof NotesRouteWithChildren
  '/$noteId': typeof NotesNoteIdIndexRoute
  '/create': typeof NotesCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof NotesRouteWithChildren
  '/$noteId': typeof NotesNoteIdIndexRoute
  '/create': typeof NotesCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_notes': typeof NotesRouteWithChildren
  '/_notes/$noteId/': typeof NotesNoteIdIndexRoute
  '/_notes/create/': typeof NotesCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/$noteId' | '/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/$noteId' | '/create'
  id: '__root__' | '/' | '/_notes' | '/_notes/$noteId/' | '/_notes/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_notes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_notes": {
      "filePath": "_notes.tsx",
      "children": [
        "/_notes/$noteId/",
        "/_notes/create/"
      ]
    },
    "/_notes/$noteId/": {
      "filePath": "_notes/$noteId/index.tsx",
      "parent": "/_notes"
    },
    "/_notes/create/": {
      "filePath": "_notes/create/index.tsx",
      "parent": "/_notes"
    }
  }
}
ROUTE_MANIFEST_END */
